language: node_js
node_js:
- '8.10'
install: yarn
script:
- yarn build
branches:
  only:
  - master
addons:
  ssh_known_hosts: 39.104.147.119
  apt:
    packages:
    - sshpass
after_success:
- export SSHPASS=$DEPLOY_PASS
- chmod -R 777 ./dist
- sshpass -e scp -o stricthostkeychecking=no -r ./dist/* $DEPLOY_USER@39.104.147.119:/home/admin-ui
env:
  global:
  - secure: okHtqhSRWTqpe3+nhDkRnKJ+fZd9F5XkUWQBRiqujzYCQQaxizGKYo3qj5jPdIHj3Na7ag2Q0sDOt93Wy/aDhLj1fnmHkGlu7eecHgm1mwwygi9ub/9bhfTierVCgSgSpotjUH5xRRP64ZUr09CPiMi33xRwaKd8OXiNDH6vxgZ7yioU3PM0sMuyQ8KHmcR+HsKuaDEt52kzwroGhjZ1kKrappwtwtFZyykEQcmcZp731blclP3dDGgvdGisPr2Crt/nzuwBC3juxIR2zGYpn4ABe4d06snyJufc3+GODxaqfyw5gFlxzOTeawLYGREkInhWrp6aUlCr1M6O7nmgVezmXRHAKr/yqKs9RP8SMk6GoERldMmJMkSyENNmmsxX5e+S5MjWnZKS0AgrkX72s5Vc76Jic5TrwoX3FSetIDh+fG4ajpEyAkjv7WhAc5ardigU+/KhEY4r7mXIe3DFC4HkWl+xpL5XKV5X2FCIXwBSFMOUBGfghaybgf8/QWMlonRF18LRI3ucCS5p7p+qF4X5woE9AGJ5ZlxEhAyLw5DQP4YoktFAr6qkp5HebQOYAua6mSwBl6Kx/NHybd3RH+kGSIp0L6SxsGl1w/EXd+zeP0McjkeyRwl2wHHTIWY+walTsMf67BB7AVFgvxm9gXM4rRjrFokztx+KemA4vPc=
  - secure: tWlOmU3uMAYgiW+UwPy5BsLNBwclR3EqDjrCYri9xLYQNxDsr7uC8ieT+y5qOXmAAGWFXiPHC+XnpA0u/gE6X6ViBeOcyZ1fcccEVwi7WDCMrHy69B/A/XLzTilfENBrMJyJqjDdDqm9Hwk0AC98MErsjQm//yaSken6tSGwQl9xAR4sR4L9QihFQJujMc3BX2bRXgYcBzHhUC0f4nCUVvJzUjzJjMkavNk7SkXDbOsW6zFHSRLvYCujLprEptGpRKngN+bLG1v/r55v5G9//DtK1hIc6iSbQzAFQo842o8/Zo3wXC2/qPRi26y257aeh93u1mMzvVtONbb3jhmM4an6/5shL06zYprjw3FeQNfZAayWsDMln7x7H7MoCIuAHsgyFMOHfRJ44dj1HqZ3JkTfXEdOTCs3BJz8aGAVho4qFdripVNfuxyU9V1q74cIpbK8HeOQNlcWFfyo1oUPjCK4MyftYNKg7QP6GdD5Bzie3VCyisW4+hkNbwK8r1PVeaLTE3c8tCPVIf1bFIKSBJV5g81/Gbv4aO4AK0ZCuzHz/IqMEG5fkamEu45n86NggOBzv2F0OBhs4jcgpzD8LHtrPvUBfkRW1FWOIYIwJlPVIVBsNzVdNOiivsPIivKUlNIpCGb3xWi2jwxfkttkywpzOZwj+fhs00W3wNI3M8w=
